"""Build the EEZ Studio UI for all boards.

eez/uaDash.eez-project (800x480) is the design that is edited in EEZ Studio.
This script
  1. builds it with EEZ Studio (command line) into firmware/src/ui_eez/800x480,
  2. generates eez/uaDash_1024x600.eez-project (everything scaled by 1.25, fonts
     regenerated, images resampled, centered on 1024x600) and builds it into
     firmware/src/ui_eez/1024x600,
  3. guards every generated .c file with the board define, so the Arduino IDE
     (which compiles all of src/) and ESP-IDF only use the matching variant.

    python tools/eez_build.py
"""

import base64
import copy
import io
import json
import os
import subprocess
import sys

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EEZ_DIR = os.path.join(ROOT, 'eez')
PROJECT = os.path.join(EEZ_DIR, 'uaDash.eez-project')
PROJECT_HIRES = os.path.join(EEZ_DIR, 'uaDash_1024x600.eez-project')
OUT = os.path.join(ROOT, 'firmware', 'src', 'ui_eez')
EEZ_STUDIO = os.path.expandvars(r'%LOCALAPPDATA%\Programs\eezstudio\EEZ Studio.exe')

HIRES_W, HIRES_H = 1024, 600
SCALE = 1.25                      # 800x480 -> 1000x600
OFFSET_X = (HIRES_W - 800 * SCALE) / 2

# boards using the 1024x600 variant (others use 800x480)
HIRES_BOARDS = ['WAVESHARE_S3_LCD7B']

PX_STYLE_PROPS = {
    'width', 'height', 'min_width', 'max_width', 'min_height', 'max_height', 'x', 'y',
    'radius', 'pad_top', 'pad_bottom', 'pad_left', 'pad_right', 'pad_row', 'pad_column',
    'border_width', 'outline_width', 'outline_pad', 'arc_width', 'line_width',
    'shadow_width', 'shadow_ofs_x', 'shadow_ofs_y', 'shadow_spread',
    'text_letter_space', 'text_line_space', 'translate_x', 'translate_y',
}
LEFT_ALIGNS = {'TOP_LEFT', 'LEFT_MID', 'BOTTOM_LEFT', 'DEFAULT', None}
RIGHT_ALIGNS = {'TOP_RIGHT', 'RIGHT_MID', 'BOTTOM_RIGHT'}


def s(v):
    return int(round(v * SCALE)) if isinstance(v, (int, float)) and not isinstance(v, bool) else v


def scale_widget(w, top_level):
    for key, unit in (('left', 'leftUnit'), ('top', 'topUnit'), ('width', 'widthUnit'), ('height', 'heightUnit')):
        if key in w and w.get(unit, 'px') in ('px', 'content'):
            w[key] = s(w[key])
    for key in ('pivotX', 'pivotY'):
        if key in w:
            w[key] = s(w[key])
    align = None
    for part in w.get('localStyles', {}).get('definition', {}).values():
        for state, props in part.items():
            for k in list(props):
                if k in PX_STYLE_PROPS:
                    props[k] = s(props[k])
            if state == 'DEFAULT' and 'align' in props:
                align = props['align']
    if top_level and w.get('leftUnit', 'px') == 'px':
        # center the 1000px wide layout on the 1024px screen
        if align in LEFT_ALIGNS:
            w['left'] += int(OFFSET_X)
        elif align in RIGHT_ALIGNS:
            w['left'] -= int(OFFSET_X)
    for c in w.get('children', []):
        scale_widget(c, False)


def scale_bitmap(b):
    head, data = b['image'].split(',', 1)
    img = Image.open(io.BytesIO(base64.b64decode(data)))
    img = img.resize((max(1, s(img.width)), max(1, s(img.height))), Image.LANCZOS)
    buf = io.BytesIO()
    img.save(buf, 'PNG')
    b['image'] = head + ',' + base64.b64encode(buf.getvalue()).decode()


def make_hires(project):
    p = copy.deepcopy(project)
    p['settings']['general'].update({'displayWidth': HIRES_W, 'displayHeight': HIRES_H,
                                     'description': 'GENERATED by tools/eez_build.py from uaDash.eez-project, do not edit'})
    p['settings']['build']['destinationFolder'] = '../firmware/src/ui_eez/1024x600'
    for page in p['userPages']:
        page['width'], page['height'] = HIRES_W, HIRES_H
        screen = page['components'][0]
        screen['width'], screen['height'] = HIRES_W, HIRES_H
        for c in screen.get('children', []):
            scale_widget(c, True)
    for f in p['fonts']:
        f['source']['size'] = s(f['source']['size'])
        for k in ('embeddedFontFile', 'lvglBinFile', 'lvglSourceFile'):
            f.pop(k, None)    # EEZ Studio regenerates the font from the TTF
    for b in p['bitmaps']:
        scale_bitmap(b)
    return p


def eez_build(path):
    out = subprocess.run([EEZ_STUDIO, '--build-project', path], capture_output=True, text=True,
                         encoding='utf-8', errors='replace', timeout=600)
    log = out.stdout
    ok = 'Build successfully finished' in log and 'No error' in log
    print('%s: %s' % (os.path.basename(path), 'ok' if ok else 'FAILED'))
    if not ok:
        print(log)
        sys.exit(1)


def guard(folder, condition):
    begin = '#if %s  // tools/eez_build.py: board variant\n' % condition
    for name in os.listdir(folder):
        if not name.endswith('.c'):
            continue
        path = os.path.join(folder, name)
        src = open(path, encoding='utf-8').read()
        if not src.startswith('#if '):
            open(path, 'w', encoding='utf-8', newline='\n').write(begin + src + '\n#endif\n')


def widget_names(project):
    """identifier of every widget and page name"""
    names = []

    def walk(w):
        if w.get('identifier'):
            names.append(w['identifier'])
        for c in w.get('children', []):
            walk(c)
    for page in project['userPages']:
        names.append(page['name'])
        for c in page['components']:
            walk(c)
    return names


def write_header(project):
    """firmware/ui_eez.h: includes the generated UI of the board and maps the SquareLine
    style names (ui_rpmWarnVal) used by the firmware to the EEZ objects (objects.rpm_warn_val)"""
    fields = []
    for line in open(os.path.join(OUT, '800x480', 'screens.h'), encoding='utf-8'):
        line = line.strip()
        if line.startswith('lv_obj_t *') and line.endswith(';'):
            fields.append(line[len('lv_obj_t *'):-1])
    by_key = {f.replace('_', ''): f for f in fields}
    defines = []
    for name in widget_names(project):
        field = by_key.get(name.replace('_', '').lower())
        if field is None:
            continue
        if name.endswith('_screen'):          # page: main_screen -> ui_mainScreen
            parts = name.split('_')
            alias = 'ui_' + parts[0] + ''.join(p.capitalize() for p in parts[1:])
        elif name.startswith('ui_'):          # already prefixed (FULLMONI design)
            continue
        else:
            alias = 'ui_' + name
        line = '#define %-36s (objects.%s)' % (alias, field)
        if line not in defines:
            defines.append(line)
    hires = ' || '.join('defined(%s)' % b for b in HIRES_BOARDS)
    with open(os.path.join(ROOT, 'firmware', 'ui_eez.h'), 'w', encoding='utf-8', newline='\n') as f:
        f.write('// GENERATED by tools/eez_build.py, do not edit\n'
                '// UI generated by EEZ Studio from eez/uaDash.eez-project for the board\n'
                '#pragma once\n\n'
                '#if %s\n#include "src/ui_eez/1024x600/ui.h"\n#include "src/ui_eez/1024x600/screens.h"\n'
                '#include "src/ui_eez/1024x600/actions.h"\n'
                '#else\n#include "src/ui_eez/800x480/ui.h"\n#include "src/ui_eez/800x480/screens.h"\n'
                '#include "src/ui_eez/800x480/actions.h"\n#endif\n\n'
                '// SquareLine style names used by updaters.cpp / events.cpp\n' % hires)
        f.write('\n'.join(defines) + '\n')


def main():
    project = json.load(open(PROJECT, encoding='utf-8'))
    build = project['settings']['build']
    if build.get('destinationFolder') != '../firmware/src/ui_eez/800x480' or build.get('lvglInclude') != 'lvgl.h':
        build['destinationFolder'] = '../firmware/src/ui_eez/800x480'
        build['lvglInclude'] = 'lvgl.h'
        with open(PROJECT, 'w', encoding='utf-8', newline='\n') as f:
            json.dump(project, f, indent=2, ensure_ascii=False)

    with open(PROJECT_HIRES, 'w', encoding='utf-8', newline='\n') as f:
        json.dump(make_hires(project), f, indent=2, ensure_ascii=False)

    for variant in ('800x480', '1024x600'):
        folder = os.path.join(OUT, variant)
        os.makedirs(folder, exist_ok=True)
        for name in os.listdir(folder):     # remove stale fonts/images
            if name.endswith(('.c', '.h')):
                os.remove(os.path.join(folder, name))

    eez_build(PROJECT)
    eez_build(PROJECT_HIRES)

    hires = ' || '.join('defined(%s)' % b for b in HIRES_BOARDS)
    guard(os.path.join(OUT, '800x480'), '!(%s)' % hires)
    guard(os.path.join(OUT, '1024x600'), hires)
    write_header(project)


if __name__ == '__main__':
    main()
