name: dash-fw-ubuntu

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  dash-fw-ubuntu:
    strategy:
      matrix:
        display: [ JC8048W550C, WAVESHARE_S3_LCD7, WAVESHARE_S3_LCD7B, WAVESHARE_S3_LCD5, Sunton_S3_LCD7 ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: echo
        run: |
          echo "::hello ${{ matrix.display }}"

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: date into header
        working-directory: firmware
        run: |
          ./current_date.sh

      # see also 0-setup.bat
      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli lib install lvgl@8.4.0
          arduino-cli lib install LovyanGFX@1.2.0
          arduino-cli lib install ESP32_IO_Expander@1.1.0
          arduino-cli core install esp32:esp32@3.2.1
      
      # - name: Configure
      #   working-directory: firmware
      #   run: |
      #     echo "#define ${{matrix.display}} 1" > config.h

      - name: Compile Sketch
        working-directory: firmware
        run: |
          arduino-cli compile -b esp32:esp32:esp32s3:FlashSize=8M,PartitionScheme=huge_app,PSRAM=opi firmware.ino -e -v --build-property "build.defines=-DBOARD_HAS_PSRAM -D${{matrix.display}}" --build-property compiler.optimization_flags=-Os

      - name: Looking at folder
        working-directory: firmware
        run: |
          ls -l
          ls -l build
          ls -l build/esp32.esp32.esp32s3

      - name: Release Manifest
        run: |
          date >> release/release.txt
          git rev-parse HEAD >> release/release.txt
          echo ${{ matrix.display }} >> release/release.txt        

      - name: Adding help into artifact folder
        run: |
          cp release/* firmware/build/

      - name: Upload .bin
        uses: actions/upload-artifact@v4
        with:
          name: "dash_${{ matrix.display }}"
          path: "firmware/build/*"

