// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: engine_settings

#ifndef UI_ENGINECONFIGSCREEN_H
#define UI_ENGINECONFIGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_engineConfigScreen
extern void ui_engineConfigScreen_screen_init(void);
extern void ui_engineConfigScreen_screen_destroy(void);
extern lv_obj_t * ui_engineConfigScreen;
extern lv_obj_t * ui_LabelEngineConf;
extern lv_obj_t * ui_LabelDisplacement;
extern lv_obj_t * ui_LabelTrigger;
extern lv_obj_t * ui_LabelCam;
extern void ui_event_CheckboxDisp48(lv_event_t * e);
extern lv_obj_t * ui_CheckboxDisp48;
extern void ui_event_CheckboxDisp53(lv_event_t * e);
extern lv_obj_t * ui_CheckboxDisp53;
extern void ui_event_CheckboxDisp57(lv_event_t * e);
extern lv_obj_t * ui_CheckboxDisp57;
extern void ui_event_CheckboxDisp60(lv_event_t * e);
extern lv_obj_t * ui_CheckboxDisp60;
extern void ui_event_CheckboxDisp62(lv_event_t * e);
extern lv_obj_t * ui_CheckboxDisp62;
extern void ui_event_CheckboxDisp70(lv_event_t * e);
extern lv_obj_t * ui_CheckboxDisp70;
extern void ui_event_CheckboxTrig24(lv_event_t * e);
extern lv_obj_t * ui_CheckboxTrig24;
extern void ui_event_CheckboxTrig58(lv_event_t * e);
extern lv_obj_t * ui_CheckboxTrig58;
extern void ui_event_CheckboxCamshape1(lv_event_t * e);
extern lv_obj_t * ui_CheckboxCamshape1;
extern void ui_event_CheckboxCamshape2(lv_event_t * e);
extern lv_obj_t * ui_CheckboxCamshape2;
extern void ui_event_CheckboxCamshape4(lv_event_t * e);
extern lv_obj_t * ui_CheckboxCamshape4;
extern void ui_event_engConfSaveButton(lv_event_t * e);
extern lv_obj_t * ui_engConfSaveButton;
extern lv_obj_t * ui_LabelSave;
extern void ui_event_engConfBackButton(lv_event_t * e);
extern lv_obj_t * ui_engConfBackButton;
extern lv_obj_t * ui_LabelBack;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

