// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_settingsScreen = NULL;
lv_obj_t * ui_labelSettingsScreen = NULL;
lv_obj_t * ui_rpmWarnContainer = NULL;
lv_obj_t * ui_rpmWarnButtonPlus = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_rpmWarnVal = NULL;
lv_obj_t * ui_rpmWarningLabel = NULL;
lv_obj_t * ui_rpmWarnButtonMinus = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_cltWarnContainer = NULL;
lv_obj_t * ui_cltWarnButtonPlus = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_cltWarnVal = NULL;
lv_obj_t * ui_cltWarnButtonMinus = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_cltWarningLabel = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_iatWarnContainer = NULL;
lv_obj_t * ui_iatWarnButtonPlus = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_iatWarnVal = NULL;
lv_obj_t * ui_iatWarnButtonMinus = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_iatWarningLabel = NULL;
lv_obj_t * ui_oilTWarnContainer = NULL;
lv_obj_t * ui_oilTWarnButtonPlus = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_oilTWarnVal = NULL;
lv_obj_t * ui_oilTWarnButtonMinus = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_oilTWarningLabel = NULL;
lv_obj_t * ui_oilPWarnContainer = NULL;
lv_obj_t * ui_oilPWarnButtonPlus = NULL;
lv_obj_t * ui_Label88 = NULL;
lv_obj_t * ui_oilPWarnVal = NULL;
lv_obj_t * ui_oilPWarnButtonMinus = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_oilPWarningLabel = NULL;
lv_obj_t * ui_fuelPWarnContainer = NULL;
lv_obj_t * ui_fuelPWarnButtonPlus = NULL;
lv_obj_t * ui_Label23 = NULL;
lv_obj_t * ui_fuelPWarnVal = NULL;
lv_obj_t * ui_fuelPWarnButtonMinus = NULL;
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_fuelPWarningLabel = NULL;
lv_obj_t * ui_vBattWarnContainer = NULL;
lv_obj_t * ui_vBattWarnButtonPlus = NULL;
lv_obj_t * ui_Label26 = NULL;
lv_obj_t * ui_vBattWarnVal = NULL;
lv_obj_t * ui_vBattWarnButtonMinus = NULL;
lv_obj_t * ui_Label27 = NULL;
lv_obj_t * ui_Label28 = NULL;
lv_obj_t * ui_vBattWarningLabel = NULL;
lv_obj_t * ui_turboMapLabel = NULL;
lv_obj_t * ui_turboSwitch = NULL;
lv_obj_t * ui_saveButton = NULL;
lv_obj_t * ui_Label29 = NULL;
lv_obj_t * ui_defaultWarnSettingsButton = NULL;
lv_obj_t * ui_Label30 = NULL;
lv_obj_t * ui_FWLabel = NULL;
lv_obj_t * ui_FWValLabel = NULL;
// event funtions
void ui_event_settingsScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_mainScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_mainScreen_screen_init);
        _ui_screen_delete(&ui_settingsScreen);
    }
}

void ui_event_rpmWarnButtonPlus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        rpmWarnSetPlus(e);
    }
}

void ui_event_rpmWarnButtonMinus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        rpmWarnSetMinus(e);
    }
}

void ui_event_cltWarnButtonPlus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        cltWarnSetPlus(e);
    }
}

void ui_event_cltWarnButtonMinus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        cltWarnSetMinus(e);
    }
}

void ui_event_iatWarnButtonPlus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        iatWarnSetPlus(e);
    }
}

void ui_event_iatWarnButtonMinus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        iatWarnSetMinus(e);
    }
}

void ui_event_oilTWarnButtonPlus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        oilTWarnSetPlus(e);
    }
}

void ui_event_oilTWarnButtonMinus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        oilTWarnSetMinus(e);
    }
}

void ui_event_oilPWarnButtonPlus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        oilPWarnSetPlus(e);
    }
}

void ui_event_oilPWarnButtonMinus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        oilPWarnSetMinus(e);
    }
}

void ui_event_fuelPWarnButtonPlus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        fuelPWarnSetPlus(e);
    }
}

void ui_event_fuelPWarnButtonMinus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        fuelPWarnSetMinus(e);
    }
}

void ui_event_vBattWarnButtonPlus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        vBattWarnSetPlus(e);
    }
}

void ui_event_vBattWarnButtonMinus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        vBattWarnSetMinus(e);
    }
}

void ui_event_turboSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if((event_code == LV_EVENT_VALUE_CHANGED) &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        setIsTurbo(e);
    }
    if((event_code == LV_EVENT_VALUE_CHANGED) &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        setIsNaturalA(e);
    }
}

void ui_event_saveButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        saveWarnSet(e);
    }
}

void ui_event_defaultWarnSettingsButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        defaultWarnSet(e);
    }
}

// build funtions

void ui_settingsScreen_screen_init(void)
{
    ui_settingsScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_settingsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settingsScreen, lv_color_hex(0x313131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settingsScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelSettingsScreen = lv_label_create(ui_settingsScreen);
    lv_obj_set_width(ui_labelSettingsScreen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelSettingsScreen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelSettingsScreen, UI_SX(-1));
    lv_obj_set_y(ui_labelSettingsScreen, UI_SY(-219));
    lv_obj_set_align(ui_labelSettingsScreen, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelSettingsScreen, "WARNING SETTINGS");
    lv_obj_set_style_text_color(ui_labelSettingsScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelSettingsScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelSettingsScreen, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpmWarnContainer = lv_obj_create(ui_settingsScreen);
    lv_obj_remove_style_all(ui_rpmWarnContainer);
    lv_obj_set_width(ui_rpmWarnContainer, UI_SX(660));
    lv_obj_set_height(ui_rpmWarnContainer, UI_SY(34));
    lv_obj_set_x(ui_rpmWarnContainer, UI_SX(80));
    lv_obj_set_y(ui_rpmWarnContainer, UI_SY(40));
    lv_obj_clear_flag(ui_rpmWarnContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rpmWarnButtonPlus = lv_btn_create(ui_rpmWarnContainer);
    lv_obj_set_width(ui_rpmWarnButtonPlus, UI_SX(50));
    lv_obj_set_height(ui_rpmWarnButtonPlus, UI_SY(28));
    lv_obj_set_x(ui_rpmWarnButtonPlus, UI_SX(-1));
    lv_obj_set_y(ui_rpmWarnButtonPlus, UI_SY(1));
    lv_obj_set_align(ui_rpmWarnButtonPlus, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_rpmWarnButtonPlus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_rpmWarnButtonPlus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_rpmWarnButtonPlus, UI_S(5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rpmWarnButtonPlus, lv_color_hex(0xE0FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rpmWarnButtonPlus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_rpmWarnButtonPlus);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "+");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &UI_FONT_MONTSERRAT_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpmWarnVal = lv_label_create(ui_rpmWarnContainer);
    lv_obj_set_width(ui_rpmWarnVal, UI_SX(120));
    lv_obj_set_height(ui_rpmWarnVal, UI_SY(18));
    lv_obj_set_x(ui_rpmWarnVal, UI_SX(250));
    lv_obj_set_y(ui_rpmWarnVal, UI_SY(10));
    lv_label_set_text(ui_rpmWarnVal, "7000");
    lv_obj_set_style_text_color(ui_rpmWarnVal, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rpmWarnVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_rpmWarnVal, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rpmWarnVal, &ui_font_FontRPM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpmWarningLabel = lv_label_create(ui_rpmWarnContainer);
    lv_obj_set_width(ui_rpmWarningLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpmWarningLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpmWarningLabel, UI_SX(0));
    lv_obj_set_y(ui_rpmWarningLabel, UI_SY(8));
    lv_label_set_text(ui_rpmWarningLabel, "rpm warning");
    lv_obj_set_style_text_color(ui_rpmWarningLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rpmWarningLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rpmWarningLabel, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpmWarnButtonMinus = lv_btn_create(ui_rpmWarnContainer);
    lv_obj_set_width(ui_rpmWarnButtonMinus, UI_SX(50));
    lv_obj_set_height(ui_rpmWarnButtonMinus, UI_SY(28));
    lv_obj_set_x(ui_rpmWarnButtonMinus, UI_SX(-90));
    lv_obj_set_y(ui_rpmWarnButtonMinus, UI_SY(1));
    lv_obj_set_align(ui_rpmWarnButtonMinus, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_rpmWarnButtonMinus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_rpmWarnButtonMinus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_rpmWarnButtonMinus, UI_S(5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rpmWarnButtonMinus, lv_color_hex(0xE0FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rpmWarnButtonMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_rpmWarnButtonMinus);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "-");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &UI_FONT_MONTSERRAT_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_rpmWarnContainer);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, UI_SX(81));
    lv_obj_set_y(ui_Label20, UI_SY(-4));
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "rpm");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cltWarnContainer = lv_obj_create(ui_settingsScreen);
    lv_obj_remove_style_all(ui_cltWarnContainer);
    lv_obj_set_width(ui_cltWarnContainer, UI_SX(660));
    lv_obj_set_height(ui_cltWarnContainer, UI_SY(34));
    lv_obj_set_x(ui_cltWarnContainer, UI_SX(80));
    lv_obj_set_y(ui_cltWarnContainer, UI_SY(90));
    lv_obj_clear_flag(ui_cltWarnContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cltWarnButtonPlus = lv_btn_create(ui_cltWarnContainer);
    lv_obj_set_width(ui_cltWarnButtonPlus, UI_SX(50));
    lv_obj_set_height(ui_cltWarnButtonPlus, UI_SY(28));
    lv_obj_set_x(ui_cltWarnButtonPlus, UI_SX(-1));
    lv_obj_set_y(ui_cltWarnButtonPlus, UI_SY(1));
    lv_obj_set_align(ui_cltWarnButtonPlus, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_cltWarnButtonPlus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_cltWarnButtonPlus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_cltWarnButtonPlus, UI_S(5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cltWarnButtonPlus, lv_color_hex(0xE0FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cltWarnButtonPlus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_cltWarnButtonPlus);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "+");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &UI_FONT_MONTSERRAT_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cltWarnVal = lv_label_create(ui_cltWarnContainer);
    lv_obj_set_width(ui_cltWarnVal, UI_SX(120));
    lv_obj_set_height(ui_cltWarnVal, UI_SY(18));
    lv_obj_set_x(ui_cltWarnVal, UI_SX(250));
    lv_obj_set_y(ui_cltWarnVal, UI_SY(10));
    lv_label_set_text(ui_cltWarnVal, "100");
    lv_obj_set_style_text_color(ui_cltWarnVal, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cltWarnVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_cltWarnVal, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cltWarnVal, &ui_font_FontRPM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cltWarnButtonMinus = lv_btn_create(ui_cltWarnContainer);
    lv_obj_set_width(ui_cltWarnButtonMinus, UI_SX(50));
    lv_obj_set_height(ui_cltWarnButtonMinus, UI_SY(28));
    lv_obj_set_x(ui_cltWarnButtonMinus, UI_SX(-90));
    lv_obj_set_y(ui_cltWarnButtonMinus, UI_SY(1));
    lv_obj_set_align(ui_cltWarnButtonMinus, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_cltWarnButtonMinus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_cltWarnButtonMinus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_cltWarnButtonMinus, UI_S(5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cltWarnButtonMinus, lv_color_hex(0xE0FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cltWarnButtonMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_cltWarnButtonMinus);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "-");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &UI_FONT_MONTSERRAT_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cltWarningLabel = lv_label_create(ui_cltWarnContainer);
    lv_obj_set_width(ui_cltWarningLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cltWarningLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cltWarningLabel, UI_SX(0));
    lv_obj_set_y(ui_cltWarningLabel, UI_SY(8));
    lv_label_set_text(ui_cltWarningLabel, "clt warning");
    lv_obj_set_style_text_color(ui_cltWarningLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cltWarningLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cltWarningLabel, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_cltWarnContainer);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, UI_SX(61));
    lv_obj_set_y(ui_Label13, UI_SY(-4));
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "c");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iatWarnContainer = lv_obj_create(ui_settingsScreen);
    lv_obj_remove_style_all(ui_iatWarnContainer);
    lv_obj_set_width(ui_iatWarnContainer, UI_SX(660));
    lv_obj_set_height(ui_iatWarnContainer, UI_SY(34));
    lv_obj_set_x(ui_iatWarnContainer, UI_SX(80));
    lv_obj_set_y(ui_iatWarnContainer, UI_SY(145));
    lv_obj_clear_flag(ui_iatWarnContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_iatWarnButtonPlus = lv_btn_create(ui_iatWarnContainer);
    lv_obj_set_width(ui_iatWarnButtonPlus, UI_SX(50));
    lv_obj_set_height(ui_iatWarnButtonPlus, UI_SY(28));
    lv_obj_set_x(ui_iatWarnButtonPlus, UI_SX(-1));
    lv_obj_set_y(ui_iatWarnButtonPlus, UI_SY(1));
    lv_obj_set_align(ui_iatWarnButtonPlus, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_iatWarnButtonPlus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_iatWarnButtonPlus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_iatWarnButtonPlus, UI_S(5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_iatWarnButtonPlus, lv_color_hex(0xE0FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_iatWarnButtonPlus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_iatWarnButtonPlus);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "+");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &UI_FONT_MONTSERRAT_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iatWarnVal = lv_label_create(ui_iatWarnContainer);
    lv_obj_set_width(ui_iatWarnVal, UI_SX(120));
    lv_obj_set_height(ui_iatWarnVal, UI_SY(18));
    lv_obj_set_x(ui_iatWarnVal, UI_SX(250));
    lv_obj_set_y(ui_iatWarnVal, UI_SY(10));
    lv_label_set_text(ui_iatWarnVal, "40");
    lv_obj_set_style_text_color(ui_iatWarnVal, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_iatWarnVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_iatWarnVal, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_iatWarnVal, &ui_font_FontRPM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iatWarnButtonMinus = lv_btn_create(ui_iatWarnContainer);
    lv_obj_set_width(ui_iatWarnButtonMinus, UI_SX(50));
    lv_obj_set_height(ui_iatWarnButtonMinus, UI_SY(28));
    lv_obj_set_x(ui_iatWarnButtonMinus, UI_SX(-90));
    lv_obj_set_y(ui_iatWarnButtonMinus, UI_SY(1));
    lv_obj_set_align(ui_iatWarnButtonMinus, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_iatWarnButtonMinus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_iatWarnButtonMinus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_iatWarnButtonMinus, UI_S(5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_iatWarnButtonMinus, lv_color_hex(0xE0FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_iatWarnButtonMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_iatWarnButtonMinus);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "-");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &UI_FONT_MONTSERRAT_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_iatWarnContainer);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, UI_SX(61));
    lv_obj_set_y(ui_Label16, UI_SY(-4));
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "c");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iatWarningLabel = lv_label_create(ui_iatWarnContainer);
    lv_obj_set_width(ui_iatWarningLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iatWarningLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_iatWarningLabel, UI_SX(0));
    lv_obj_set_y(ui_iatWarningLabel, UI_SY(8));
    lv_label_set_text(ui_iatWarningLabel, "iat warning");
    lv_obj_set_style_text_color(ui_iatWarningLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_iatWarningLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_iatWarningLabel, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_oilTWarnContainer = lv_obj_create(ui_settingsScreen);
    lv_obj_remove_style_all(ui_oilTWarnContainer);
    lv_obj_set_width(ui_oilTWarnContainer, UI_SX(660));
    lv_obj_set_height(ui_oilTWarnContainer, UI_SY(34));
    lv_obj_set_x(ui_oilTWarnContainer, UI_SX(80));
    lv_obj_set_y(ui_oilTWarnContainer, UI_SY(200));
    lv_obj_clear_flag(ui_oilTWarnContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_oilTWarnButtonPlus = lv_btn_create(ui_oilTWarnContainer);
    lv_obj_set_width(ui_oilTWarnButtonPlus, UI_SX(50));
    lv_obj_set_height(ui_oilTWarnButtonPlus, UI_SY(28));
    lv_obj_set_x(ui_oilTWarnButtonPlus, UI_SX(-1));
    lv_obj_set_y(ui_oilTWarnButtonPlus, UI_SY(1));
    lv_obj_set_align(ui_oilTWarnButtonPlus, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_oilTWarnButtonPlus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_oilTWarnButtonPlus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_oilTWarnButtonPlus, UI_S(5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_oilTWarnButtonPlus, lv_color_hex(0xE0FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_oilTWarnButtonPlus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_oilTWarnButtonPlus);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "+");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &UI_FONT_MONTSERRAT_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_oilTWarnVal = lv_label_create(ui_oilTWarnContainer);
    lv_obj_set_width(ui_oilTWarnVal, UI_SX(120));
    lv_obj_set_height(ui_oilTWarnVal, UI_SY(18));
    lv_obj_set_x(ui_oilTWarnVal, UI_SX(250));
    lv_obj_set_y(ui_oilTWarnVal, UI_SY(10));
    lv_label_set_text(ui_oilTWarnVal, "110");
    lv_obj_set_style_text_color(ui_oilTWarnVal, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_oilTWarnVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_oilTWarnVal, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_oilTWarnVal, &ui_font_FontRPM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_oilTWarnButtonMinus = lv_btn_create(ui_oilTWarnContainer);
    lv_obj_set_width(ui_oilTWarnButtonMinus, UI_SX(50));
    lv_obj_set_height(ui_oilTWarnButtonMinus, UI_SY(28));
    lv_obj_set_x(ui_oilTWarnButtonMinus, UI_SX(-90));
    lv_obj_set_y(ui_oilTWarnButtonMinus, UI_SY(1));
    lv_obj_set_align(ui_oilTWarnButtonMinus, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_oilTWarnButtonMinus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_oilTWarnButtonMinus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_oilTWarnButtonMinus, UI_S(5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_oilTWarnButtonMinus, lv_color_hex(0xE0FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_oilTWarnButtonMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_oilTWarnButtonMinus);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "-");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &UI_FONT_MONTSERRAT_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_oilTWarnContainer);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, UI_SX(61));
    lv_obj_set_y(ui_Label19, UI_SY(-4));
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "c");
    lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label19, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_oilTWarningLabel = lv_label_create(ui_oilTWarnContainer);
    lv_obj_set_width(ui_oilTWarningLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_oilTWarningLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_oilTWarningLabel, UI_SX(0));
    lv_obj_set_y(ui_oilTWarningLabel, UI_SY(8));
    lv_label_set_text(ui_oilTWarningLabel, "oil t warning");
    lv_obj_set_style_text_color(ui_oilTWarningLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_oilTWarningLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_oilTWarningLabel, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_oilPWarnContainer = lv_obj_create(ui_settingsScreen);
    lv_obj_remove_style_all(ui_oilPWarnContainer);
    lv_obj_set_width(ui_oilPWarnContainer, UI_SX(660));
    lv_obj_set_height(ui_oilPWarnContainer, UI_SY(34));
    lv_obj_set_x(ui_oilPWarnContainer, UI_SX(80));
    lv_obj_set_y(ui_oilPWarnContainer, UI_SY(255));
    lv_obj_clear_flag(ui_oilPWarnContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_oilPWarnButtonPlus = lv_btn_create(ui_oilPWarnContainer);
    lv_obj_set_width(ui_oilPWarnButtonPlus, UI_SX(50));
    lv_obj_set_height(ui_oilPWarnButtonPlus, UI_SY(28));
    lv_obj_set_x(ui_oilPWarnButtonPlus, UI_SX(-1));
    lv_obj_set_y(ui_oilPWarnButtonPlus, UI_SY(1));
    lv_obj_set_align(ui_oilPWarnButtonPlus, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_oilPWarnButtonPlus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_oilPWarnButtonPlus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_oilPWarnButtonPlus, UI_S(5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_oilPWarnButtonPlus, lv_color_hex(0xE0FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_oilPWarnButtonPlus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label88 = lv_label_create(ui_oilPWarnButtonPlus);
    lv_obj_set_width(ui_Label88, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label88, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label88, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label88, "+");
    lv_obj_set_style_text_color(ui_Label88, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label88, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label88, &UI_FONT_MONTSERRAT_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_oilPWarnVal = lv_label_create(ui_oilPWarnContainer);
    lv_obj_set_width(ui_oilPWarnVal, UI_SX(120));
    lv_obj_set_height(ui_oilPWarnVal, UI_SY(18));
    lv_obj_set_x(ui_oilPWarnVal, UI_SX(250));
    lv_obj_set_y(ui_oilPWarnVal, UI_SY(10));
    lv_label_set_text(ui_oilPWarnVal, "1.8");
    lv_obj_set_style_text_color(ui_oilPWarnVal, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_oilPWarnVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_oilPWarnVal, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_oilPWarnVal, &ui_font_FontRPM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_oilPWarnButtonMinus = lv_btn_create(ui_oilPWarnContainer);
    lv_obj_set_width(ui_oilPWarnButtonMinus, UI_SX(50));
    lv_obj_set_height(ui_oilPWarnButtonMinus, UI_SY(28));
    lv_obj_set_x(ui_oilPWarnButtonMinus, UI_SX(-90));
    lv_obj_set_y(ui_oilPWarnButtonMinus, UI_SY(1));
    lv_obj_set_align(ui_oilPWarnButtonMinus, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_oilPWarnButtonMinus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_oilPWarnButtonMinus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_oilPWarnButtonMinus, UI_S(5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_oilPWarnButtonMinus, lv_color_hex(0xE0FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_oilPWarnButtonMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_oilPWarnButtonMinus);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "-");
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label21, &UI_FONT_MONTSERRAT_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_oilPWarnContainer);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, UI_SX(79));
    lv_obj_set_y(ui_Label22, UI_SY(-4));
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "bar");
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label22, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_oilPWarningLabel = lv_label_create(ui_oilPWarnContainer);
    lv_obj_set_width(ui_oilPWarningLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_oilPWarningLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_oilPWarningLabel, UI_SX(0));
    lv_obj_set_y(ui_oilPWarningLabel, UI_SY(8));
    lv_label_set_text(ui_oilPWarningLabel, "oil p warning");
    lv_obj_set_style_text_color(ui_oilPWarningLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_oilPWarningLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_oilPWarningLabel, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fuelPWarnContainer = lv_obj_create(ui_settingsScreen);
    lv_obj_remove_style_all(ui_fuelPWarnContainer);
    lv_obj_set_width(ui_fuelPWarnContainer, UI_SX(660));
    lv_obj_set_height(ui_fuelPWarnContainer, UI_SY(34));
    lv_obj_set_x(ui_fuelPWarnContainer, UI_SX(80));
    lv_obj_set_y(ui_fuelPWarnContainer, UI_SY(310));
    lv_obj_clear_flag(ui_fuelPWarnContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_fuelPWarnButtonPlus = lv_btn_create(ui_fuelPWarnContainer);
    lv_obj_set_width(ui_fuelPWarnButtonPlus, UI_SX(50));
    lv_obj_set_height(ui_fuelPWarnButtonPlus, UI_SY(28));
    lv_obj_set_x(ui_fuelPWarnButtonPlus, UI_SX(-1));
    lv_obj_set_y(ui_fuelPWarnButtonPlus, UI_SY(1));
    lv_obj_set_align(ui_fuelPWarnButtonPlus, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_fuelPWarnButtonPlus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_fuelPWarnButtonPlus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_fuelPWarnButtonPlus, UI_S(5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_fuelPWarnButtonPlus, lv_color_hex(0xE0FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fuelPWarnButtonPlus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_fuelPWarnButtonPlus);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "+");
    lv_obj_set_style_text_color(ui_Label23, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label23, &UI_FONT_MONTSERRAT_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fuelPWarnVal = lv_label_create(ui_fuelPWarnContainer);
    lv_obj_set_width(ui_fuelPWarnVal, UI_SX(120));
    lv_obj_set_height(ui_fuelPWarnVal, UI_SY(18));
    lv_obj_set_x(ui_fuelPWarnVal, UI_SX(250));
    lv_obj_set_y(ui_fuelPWarnVal, UI_SY(10));
    lv_label_set_text(ui_fuelPWarnVal, "2.5");
    lv_obj_set_style_text_color(ui_fuelPWarnVal, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_fuelPWarnVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_fuelPWarnVal, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_fuelPWarnVal, &ui_font_FontRPM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fuelPWarnButtonMinus = lv_btn_create(ui_fuelPWarnContainer);
    lv_obj_set_width(ui_fuelPWarnButtonMinus, UI_SX(50));
    lv_obj_set_height(ui_fuelPWarnButtonMinus, UI_SY(28));
    lv_obj_set_x(ui_fuelPWarnButtonMinus, UI_SX(-90));
    lv_obj_set_y(ui_fuelPWarnButtonMinus, UI_SY(1));
    lv_obj_set_align(ui_fuelPWarnButtonMinus, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_fuelPWarnButtonMinus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_fuelPWarnButtonMinus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_fuelPWarnButtonMinus, UI_S(5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_fuelPWarnButtonMinus, lv_color_hex(0xE0FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fuelPWarnButtonMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_fuelPWarnButtonMinus);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "-");
    lv_obj_set_style_text_color(ui_Label24, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label24, &UI_FONT_MONTSERRAT_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_fuelPWarnContainer);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, UI_SX(79));
    lv_obj_set_y(ui_Label25, UI_SY(-4));
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "bar");
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label25, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fuelPWarningLabel = lv_label_create(ui_fuelPWarnContainer);
    lv_obj_set_width(ui_fuelPWarningLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fuelPWarningLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fuelPWarningLabel, UI_SX(0));
    lv_obj_set_y(ui_fuelPWarningLabel, UI_SY(8));
    lv_label_set_text(ui_fuelPWarningLabel, "fuel p warning");
    lv_obj_set_style_text_color(ui_fuelPWarningLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_fuelPWarningLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_fuelPWarningLabel, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vBattWarnContainer = lv_obj_create(ui_settingsScreen);
    lv_obj_remove_style_all(ui_vBattWarnContainer);
    lv_obj_set_width(ui_vBattWarnContainer, UI_SX(660));
    lv_obj_set_height(ui_vBattWarnContainer, UI_SY(34));
    lv_obj_set_x(ui_vBattWarnContainer, UI_SX(80));
    lv_obj_set_y(ui_vBattWarnContainer, UI_SY(365));
    lv_obj_clear_flag(ui_vBattWarnContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_vBattWarnButtonPlus = lv_btn_create(ui_vBattWarnContainer);
    lv_obj_set_width(ui_vBattWarnButtonPlus, UI_SX(50));
    lv_obj_set_height(ui_vBattWarnButtonPlus, UI_SY(28));
    lv_obj_set_x(ui_vBattWarnButtonPlus, UI_SX(-1));
    lv_obj_set_y(ui_vBattWarnButtonPlus, UI_SY(1));
    lv_obj_set_align(ui_vBattWarnButtonPlus, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_vBattWarnButtonPlus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_vBattWarnButtonPlus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_vBattWarnButtonPlus, UI_S(5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_vBattWarnButtonPlus, lv_color_hex(0xE0FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_vBattWarnButtonPlus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_vBattWarnButtonPlus);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "+");
    lv_obj_set_style_text_color(ui_Label26, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label26, &UI_FONT_MONTSERRAT_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vBattWarnVal = lv_label_create(ui_vBattWarnContainer);
    lv_obj_set_width(ui_vBattWarnVal, UI_SX(120));
    lv_obj_set_height(ui_vBattWarnVal, UI_SY(18));
    lv_obj_set_x(ui_vBattWarnVal, UI_SX(250));
    lv_obj_set_y(ui_vBattWarnVal, UI_SY(10));
    lv_label_set_text(ui_vBattWarnVal, "12.5");
    lv_obj_set_style_text_color(ui_vBattWarnVal, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_vBattWarnVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_vBattWarnVal, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_vBattWarnVal, &ui_font_FontRPM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vBattWarnButtonMinus = lv_btn_create(ui_vBattWarnContainer);
    lv_obj_set_width(ui_vBattWarnButtonMinus, UI_SX(50));
    lv_obj_set_height(ui_vBattWarnButtonMinus, UI_SY(28));
    lv_obj_set_x(ui_vBattWarnButtonMinus, UI_SX(-90));
    lv_obj_set_y(ui_vBattWarnButtonMinus, UI_SY(1));
    lv_obj_set_align(ui_vBattWarnButtonMinus, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_vBattWarnButtonMinus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_vBattWarnButtonMinus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_vBattWarnButtonMinus, UI_S(5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_vBattWarnButtonMinus, lv_color_hex(0xE0FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_vBattWarnButtonMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label27 = lv_label_create(ui_vBattWarnButtonMinus);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "-");
    lv_obj_set_style_text_color(ui_Label27, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label27, &UI_FONT_MONTSERRAT_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_vBattWarnContainer);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, UI_SX(61));
    lv_obj_set_y(ui_Label28, UI_SY(-4));
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "v");
    lv_obj_set_style_text_color(ui_Label28, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label28, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vBattWarningLabel = lv_label_create(ui_vBattWarnContainer);
    lv_obj_set_width(ui_vBattWarningLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_vBattWarningLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_vBattWarningLabel, UI_SX(0));
    lv_obj_set_y(ui_vBattWarningLabel, UI_SY(8));
    lv_label_set_text(ui_vBattWarningLabel, "vbatt warning");
    lv_obj_set_style_text_color(ui_vBattWarningLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_vBattWarningLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_vBattWarningLabel, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_turboMapLabel = lv_label_create(ui_settingsScreen);
    lv_obj_set_width(ui_turboMapLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_turboMapLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_turboMapLabel, UI_SX(80));
    lv_obj_set_y(ui_turboMapLabel, UI_SY(427));
    lv_label_set_text(ui_turboMapLabel, "map turbo");
    lv_obj_set_style_text_color(ui_turboMapLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_turboMapLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_turboMapLabel, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_turboSwitch = lv_switch_create(ui_settingsScreen);
    lv_obj_set_width(ui_turboSwitch, UI_SX(50));
    lv_obj_set_height(ui_turboSwitch, UI_SY(25));
    lv_obj_set_x(ui_turboSwitch, UI_SX(-118));
    lv_obj_set_y(ui_turboSwitch, UI_SY(196));
    lv_obj_set_align(ui_turboSwitch, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_turboSwitch, lv_color_hex(0xE0FF00), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_turboSwitch, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_turboSwitch, lv_color_hex(0x313131), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_turboSwitch, 255, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_saveButton = lv_btn_create(ui_settingsScreen);
    lv_obj_set_width(ui_saveButton, UI_SX(139));
    lv_obj_set_height(ui_saveButton, UI_SY(33));
    lv_obj_set_x(ui_saveButton, UI_SX(-61));
    lv_obj_set_y(ui_saveButton, UI_SY(-23));
    lv_obj_set_align(ui_saveButton, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_saveButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_saveButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_saveButton, UI_S(7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_saveButton, lv_color_hex(0x32A41B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_saveButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_saveButton);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, UI_SX(0));
    lv_obj_set_y(ui_Label29, UI_SY(-1));
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "SAVE");
    lv_obj_set_style_text_color(ui_Label29, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label29, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_defaultWarnSettingsButton = lv_btn_create(ui_settingsScreen);
    lv_obj_set_width(ui_defaultWarnSettingsButton, UI_SX(139));
    lv_obj_set_height(ui_defaultWarnSettingsButton, UI_SY(33));
    lv_obj_set_x(ui_defaultWarnSettingsButton, UI_SX(-240));
    lv_obj_set_y(ui_defaultWarnSettingsButton, UI_SY(-23));
    lv_obj_set_align(ui_defaultWarnSettingsButton, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_defaultWarnSettingsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_defaultWarnSettingsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_defaultWarnSettingsButton, UI_S(7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_defaultWarnSettingsButton, lv_color_hex(0x32A41B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_defaultWarnSettingsButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_defaultWarnSettingsButton);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, UI_SX(0));
    lv_obj_set_y(ui_Label30, UI_SY(-1));
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "default");
    lv_obj_set_style_text_color(ui_Label30, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label30, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FWLabel = lv_label_create(ui_settingsScreen);
    lv_obj_set_width(ui_FWLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FWLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FWLabel, UI_SX(4));
    lv_obj_set_y(ui_FWLabel, UI_SY(-1));
    lv_obj_set_align(ui_FWLabel, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_FWLabel, "FW:");
    lv_obj_set_style_text_color(ui_FWLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FWLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FWLabel, &ui_font_FontIndicatorLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FWValLabel = lv_label_create(ui_settingsScreen);
    lv_obj_set_width(ui_FWValLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FWValLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FWValLabel, UI_SX(35));
    lv_obj_set_y(ui_FWValLabel, UI_SY(-1));
    lv_obj_set_align(ui_FWValLabel, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_FWValLabel, "XXX-xxx");
    lv_obj_set_style_text_color(ui_FWValLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FWValLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FWValLabel, &ui_font_FontIndicatorLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_rpmWarnButtonPlus, ui_event_rpmWarnButtonPlus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_rpmWarnButtonMinus, ui_event_rpmWarnButtonMinus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cltWarnButtonPlus, ui_event_cltWarnButtonPlus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cltWarnButtonMinus, ui_event_cltWarnButtonMinus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_iatWarnButtonPlus, ui_event_iatWarnButtonPlus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_iatWarnButtonMinus, ui_event_iatWarnButtonMinus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_oilTWarnButtonPlus, ui_event_oilTWarnButtonPlus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_oilTWarnButtonMinus, ui_event_oilTWarnButtonMinus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_oilPWarnButtonPlus, ui_event_oilPWarnButtonPlus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_oilPWarnButtonMinus, ui_event_oilPWarnButtonMinus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_fuelPWarnButtonPlus, ui_event_fuelPWarnButtonPlus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_fuelPWarnButtonMinus, ui_event_fuelPWarnButtonMinus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_vBattWarnButtonPlus, ui_event_vBattWarnButtonPlus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_vBattWarnButtonMinus, ui_event_vBattWarnButtonMinus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_saveButton, ui_event_saveButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_defaultWarnSettingsButton, ui_event_defaultWarnSettingsButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settingsScreen, ui_event_settingsScreen, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_turboSwitch, ui_event_turboSwitch, LV_EVENT_ALL, NULL);
}

void ui_settingsScreen_screen_destroy(void)
{
    if(ui_settingsScreen) lv_obj_del(ui_settingsScreen);

    // NULL screen variables
    ui_settingsScreen = NULL;
    ui_labelSettingsScreen = NULL;
    ui_rpmWarnContainer = NULL;
    ui_rpmWarnButtonPlus = NULL;
    ui_Label9 = NULL;
    ui_rpmWarnVal = NULL;
    ui_rpmWarningLabel = NULL;
    ui_rpmWarnButtonMinus = NULL;
    ui_Label10 = NULL;
    ui_Label20 = NULL;
    ui_cltWarnContainer = NULL;
    ui_cltWarnButtonPlus = NULL;
    ui_Label11 = NULL;
    ui_cltWarnVal = NULL;
    ui_cltWarnButtonMinus = NULL;
    ui_Label12 = NULL;
    ui_cltWarningLabel = NULL;
    ui_Label13 = NULL;
    ui_iatWarnContainer = NULL;
    ui_iatWarnButtonPlus = NULL;
    ui_Label14 = NULL;
    ui_iatWarnVal = NULL;
    ui_iatWarnButtonMinus = NULL;
    ui_Label15 = NULL;
    ui_Label16 = NULL;
    ui_iatWarningLabel = NULL;
    ui_oilTWarnContainer = NULL;
    ui_oilTWarnButtonPlus = NULL;
    ui_Label17 = NULL;
    ui_oilTWarnVal = NULL;
    ui_oilTWarnButtonMinus = NULL;
    ui_Label18 = NULL;
    ui_Label19 = NULL;
    ui_oilTWarningLabel = NULL;
    ui_oilPWarnContainer = NULL;
    ui_oilPWarnButtonPlus = NULL;
    ui_Label88 = NULL;
    ui_oilPWarnVal = NULL;
    ui_oilPWarnButtonMinus = NULL;
    ui_Label21 = NULL;
    ui_Label22 = NULL;
    ui_oilPWarningLabel = NULL;
    ui_fuelPWarnContainer = NULL;
    ui_fuelPWarnButtonPlus = NULL;
    ui_Label23 = NULL;
    ui_fuelPWarnVal = NULL;
    ui_fuelPWarnButtonMinus = NULL;
    ui_Label24 = NULL;
    ui_Label25 = NULL;
    ui_fuelPWarningLabel = NULL;
    ui_vBattWarnContainer = NULL;
    ui_vBattWarnButtonPlus = NULL;
    ui_Label26 = NULL;
    ui_vBattWarnVal = NULL;
    ui_vBattWarnButtonMinus = NULL;
    ui_Label27 = NULL;
    ui_Label28 = NULL;
    ui_vBattWarningLabel = NULL;
    ui_turboMapLabel = NULL;
    ui_turboSwitch = NULL;
    ui_saveButton = NULL;
    ui_Label29 = NULL;
    ui_defaultWarnSettingsButton = NULL;
    ui_Label30 = NULL;
    ui_FWLabel = NULL;
    ui_FWValLabel = NULL;
}
